# -*- coding: utf-8 -*-
"""Regressao_Linear_Simples_PIB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ONgL4rrba8dTiXa7LN0f9n5dE843WXy
"""

#importando as bibliotecas
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

#carga dos dados | Fonte dados públicos: Itaú BBA
df=pd.read_csv('https://raw.githubusercontent.com/diogenesjusto/FIAP-On-Line-Graduation/refs/heads/main/datasets/pib.csv')

#analise de correlação das variáveis
graf = df.iloc[:,2:5]
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = [15, 4]

fig, ax = plt.subplots()

graf.plot(ax=ax)
plt.show()

"""* A linha azul do PIB tem uma queda acentuada um pouco antes do mês 60 no eixo X. O dataset inicia em 2004, 60 meses após jan/04 seriam 5 anos, ou seja, o ano de 2008. Isso seria explicado pela crise econômica mundial ocorrida naquele ano.

* Existe um padrão notado nas três linhas. A linha BRL, se refere ao tráfego de veículos leves inicia em queda e, depois de um ano tem uma alta. E se mantem dessa forma por 2 a 3 meses e volta a cair. Essa repetição de padrão é chamada de sazonalidade. E correlacionando com nossa realidade, faz sentido o aumento do tráfego nas férias de fim de ano e início do ano novo.

* As linhas BRL e BRP(tráfego de veículos pesados) parecem andar em movimentos contrários. Correlacionando mais uma vez, em épocas de férias e fim de ano, há uma redução do tráfego de caminhões.
"""

#correlação das variáveis
df_corr = df.iloc[:,2:15]
df_corr.corr()

#matriz visual de correlação

f = plt.figure(figsize=(8, 8))
plt.matshow(df_corr.corr())
plt.xticks(range(df_corr.select_dtypes(['number']).shape[1]), df_corr.select_dtypes(['number']).columns, fontsize=9, rotation=45)
plt.yticks(range(df_corr.select_dtypes(['number']).shape[1]), df_corr.select_dtypes(['number']).columns, fontsize=9)
cb = plt.colorbar()
cb.ax.tick_params(labelsize=10)
plt.title('Correlation Matrix', fontsize=16);

"""Assim fica mais fácil visualizar as correlações através das cores. Sendo as mais claras (mais pro amarelo) as com correlação mais forte do que as fracas em escuro (mais pro azul).

* As variáveis com maior correlação linear são:
BRP, SPP, SPT e RJP

"""

#separação das amostras de treino e teste
x_treino, x_teste, y_treino, y_teste = train_test_split(df[['BRP', 'BRL']], df['PIB'], test_size=0.3266, random_state=33)

#construção do modelo
modelo = LinearRegression()
modelo.fit(x_treino, y_treino)

#Cálculo das estatística de regressão linear
import statsmodels.api as sm
modelo = sm.OLS(y_treino, x_treino).fit()
print(modelo.summary())

#avaliação do modelo
y_previsto = modelo.predict(x_teste)
mean_squared_error(y_teste, y_previsto)

"""* A variável BRP tem um erro quadrático de 28,73%
* A variável SPP tem um erro quadrático de 42,11%
* A variável SPT tem um erro quadrático de 88,91%
* A variável RJP tem um erro quadrático de 26,70%

###**A variável RJP é a com o menor erro (isolada).**

* As variáveis BRP e SPP tem um erro quadrático de 26,36%
* As variáveis BRP e SPT tem um erro quadrático de 21,96%
* As variáveis BRP e RJP tem um erro quadrático de 23,61%
* As variáveis SPP e SPT tem um erro quadrático de 31,14%
* As variáveis SPP e RJP tem um erro quadrático de 25,95%
* As variáveis SPT e RJP tem um erro quadrático de 21,75%

###**As variáveis combinadas SPT e RJP são as com menor erro.**

Note que curioso, ao combinar BRP com BRL temos um erro ainda menor (19,40%), ainda que BRL não esteja entre as nossas variáveis com maior correlação.

Para este caso o valor de P>|t| e o erro padrão são adequadamente baixos, mantendo sua relevância estatísca no modelo, um R² com valor alto e coeficientes indicando que BRP denota "mais peso" que BRL.

##Conclusão
Um erro menor (BRP-BRL) indica que seria um modelo com melhor performance. A observação sobre usar as variáveis BRP e BRL juntas e trazer o menor erro possível, se dá pelo fato de que, na vida que real, os veículos leves são complementares ao comportamento do tráfego de veículos pesados no nosso país. Enquanto os veículos pesados tem uma incidência maior de tráfego após o mês de março até novembro, após esse período o aumento do fluxo dos veículos leves se intensifica das férias de fim de ano até o carnaval.
"""

